---
cf_cli/cf-linux-amd64.tgz:
  object_id: 15a5eb5b-340c-46d3-a97c-e589d1ca9bdc
  sha: 0abe4fe2a4ad6a1b610009c5b959fdaadf1219a2
  size: 4743214
appdynamics-service-broker/appdynamics-service-broker.jar:
  object_id: 78e26353-8193-43aa-89d5-584cc2208d82
  sha: d72de1e7ce8645b67da7a3ac5a604347cba29df2
  size: 13332752
appdynamics-machine-agent/machineagent-bundle-64bit-linux.zip:
  object_id: ef38f03b-c10d-4b31-8832-ff877df2921c
  sha: 12fe6a5c6b0256ba5d47457d9371049fde064000
  size: 94599827
