---
appdynamics-service-broker/appdynamics-service-broker.jar:
  object_id: 9803917f-c1c8-4666-ba85-7a775e6dceeb
  sha: 9aadedc795da13ea48175b57f79a5ae09309d8ec
  size: 13332794
cf_cli/cf-linux-amd64.tgz:
  object_id: 1e3d6993-6816-4612-a82a-9ca3167c7230
  sha: 82c5774aa44af9d091d3461adfb61bdadd64aad3
  size: 5486088
appdynamics-machine-agent/machineagent-bundle-64bit-linux.zip:
  object_id: 4327d8b7-b518-4294-a437-a75006665866
  sha: a50e07b64e08fe79aeada98ed42ea6f4a0b54337
  size: 94599765
appdynamics-db-agent/dbagent-4.2.1.4.zip:
  object_id: b43f16b3-2a37-4ae4-832f-9c9738a73ea4
  sha: ce591b00822a0c99e2d9b5271f20c2c6610e00c7
  size: 39721231
appdynamics-db-agent/dbagent.zip:
  object_id: 8c243671-d4f8-475d-bfc5-a9b5eaf0cb67
  sha: cf998586dcbaea6100ca9f1bee7466144a118250
  size: 39721231
appdynamics-analytics-agent/analytics-agent.zip:
  object_id: d544c89f-e473-424d-864c-d38a0c802929
  sha: 85ff54a1b1a425e3b0ff38cff07c467f0a1ab8d1
  size: 15016680
